name: Set up cache

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-24.04

    env:
      MGFXC_WINE_PATH: /home/runner/.winemonogame

    steps:
    - uses: actions/checkout@v4
    - name: Use universe
      run: |
        sudo add-apt-repository universe
        sudo apt update
    - name: Setup packages
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: wget curl p7zip-full wine64
        version: 1.0
